#!/usr/bin/env bash
for i in {1..10}
do
    echo "Round ${i}: Searching the SE Linux audit log (/var/log/audit/audit.log) for the '$1' service and allowing it to do whatever it wants (audit2allow -M my${1}policy)..."
    grep "$1" /var/log/audit/audit.log | audit2allow -l && grep "$1" /var/log/audit/audit.log | audit2allow -M "my${1}policy" && semodule -i "my${1}policy.pp"
    sleep 2s
done